Switch forecast.io to darksky.net
triggr/magic-mirror pull request #3
Opened 2016-10-26 00:23 UTC by pcsforeducation

Forecast.io is going away, and they request a "powered by" thing.

2016-10-26 00:56 UTC, Kurt-von-Laven requested changes
Not sure if there are other things that should be renamed.

2016-10-26 00:56 UTC, Kurt-von-Laven commented on forecastio/forecastio.js
> +        var url = 'https://api.darksky.net/forecast/' + FORECASTIO_KEY + '/';
Seems like `FORECASTIO_KEY` should be renamed.

2016-10-28 19:49 UTC, pcsforeducation commented
Whoops, missed pushing this last commit, which is why the forecast is broken. PTAL.

2016-10-28 20:03 UTC, Kurt-von-Laven approved these changes
Ah hah! **LGTM**

2016-10-28 20:04 UTC, merged